dist: ubuntu
language: java
jdk:
 - oraclejdk8
node_js: 
  7
env:
  global:
      - CC_TEST_REPORTER_ID=682ea1e79d2c9df44cf3f6cfb739b810b0ffcf7296a81a76ed5213f0046ac8fe
 
before_script:
 - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
 - chmod +x ./cc-test-reporter
 - ./cc-test-reporter before-build
 - npm install -g phantomjs
 - ./gradlew bootRun &
script:
 - ./gradlew partTest
 - ./gradlew cucumber

after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
